### PR TITLE
DOC: Updated links

### PR DESCRIPTION
**Pull request by visshaljagtap**

### CODE REVIEW

**Comment by dulinriley** [comment]
This looks like the same PR as #197, except it adds the change to the React link.
If you make this PR just the changes not covered in #197 then I can merge both of them.

**Comment by visshaljagtap** [comment]
Sure @dulinriley will do!

**Comment by visshaljagtap** [comment]
Done! @dulinriley Please review!

**Comment by dulinriley** [comment]
Thanks @visshaljagtap I'll merge this in!

**Pull request closed without merging**
