### PR TITLE
convert circleci workflows to github actions

### PR DESCRIPTION
**Pull request by robandpdx**
## Summary

This pull request converts the CircleCI workflows to GitHub actions workflows.  

### Errors
The `linux` job fails with the following unit test failure...

<details>
<summary>Error</summary>

```
-- Testing: 1976 tests, 4 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 
FAIL: Hermes-Unit :: VMRuntime/./HermesVMRuntimeTests/GCReturnUnusedMemoryTest.CollectReturnsFreeMemory (1808 of 1976)
******************** TEST 'Hermes-Unit :: VMRuntime/./HermesVMRuntimeTests/GCReturnUnusedMemoryTest.CollectReturnsFreeMemory' FAILED ********************
Note: Google Test filter = GCReturnUnusedMemoryTest.CollectReturnsFreeMemory
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GCReturnUnusedMemoryTest
[ RUN      ] GCReturnUnusedMemoryTest.CollectReturnsFreeMemory
/home/runner/work/hermes/hermes/hermes/unittests/VMRuntime/GCReturnUnusedMemoryTest.cpp:68: Failure
Expected: (*before) < (*touched), actual: 3009 vs 3009
[  FAILED  ] GCReturnUnusedMemoryTest.CollectReturnsFreeMemory (5 ms)
[----------] 1 test from GCReturnUnusedMemoryTest (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GCReturnUnusedMemoryTest.CollectReturnsFreeMemory

 1 FAILED TEST

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 13.21s
********************
Failing Tests (1):
    Hermes-Unit :: VMRuntime/./HermesVMRuntimeTests/GCReturnUnusedMemoryTest.CollectReturnsFreeMemory

  Expected Passes    : 1848
  Unsupported Tests  : 127
  Unexpected Failures: 1
  ```

  </details>

## Test Plan

The workflows was tested in my fork. [Here is the latest workflow run in my fork](https://github.com/robandpdx-org/hermes/actions/runs/7832320547).  

https://fburl.com/workplace/f6mz6tmw

### CODE REVIEW

**Comment by mattbfb** [comment]
Thanks for putting this together! I think the windows failures are unrelated and will have fix landing shortly. I am curious about what we could do for the android test cases that don't currently seem to be included.

**Comment by robandpdx** [comment]
> I am curious about what we could do for the android test cases that don't currently seem to be included.

If we can identify a suitable docker image for the android jobs, I'd be happy to make another PR for these. Let me know please.

**Comment by mattbfb** [comment]
@robandpdx I think we want to do largely the same as React Native here for the android tests. I see their PR is coming along as well (https://github.com/facebook/react-native/pull/42931), but it's not obvious to me how to answer the question of which docker image is being used. I think their android tests are being invoked [here](https://github.com/facebook/react-native/blob/3ed0ff34b37bb1481d0a49bac40efadfa7fde01b/scripts/e2e/run-ci-e2e-tests.js#L4).

**Comment by robandpdx** [comment]
@mattbfb Are these android tests being run in circleci currently? Can you point me to the circleci config please?

**Comment by robandpdx** [comment]
@mattbfb Thanks! I'll add that. Any idea what [this error is with the linux job in my fork](https://github.com/robandpdx-org/hermes/actions/runs/8189720757/job/22395063422)? Fresh rebase today.

**Comment by mattbfb** [comment]
@robandpdx Hm, I'm not sure. Is there any way we can debug these as they run in GitHub actions?

**Comment by robandpdx** [comment]
> @robandpdx Hm, I'm not sure. Is there any way we can debug these as they run in GitHub actions?

@mattbfb The best way to debug this is probably to run the commands from the workflow in a fresh ubuntu 20.04 linux vm.

**Comment by robandpdx** [comment]
---

The `test-e2e-intl` job fails with the following error.  
<details>
<summary>Error</summary>

```
FAILURE: Build failed with an exception.

* Where:
Build file '/__w/hermes/hermes/hermes/android/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'Hermes'.
> Hermes host build not found. Expression: (hermesC != ). Values: hermesC = 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Error: Process completed with exit code 1.
```

</details>

The `test-e2e` job fails with the following error.  
<details>
<summary>Error</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packages:rn-tester:android:app:installHermesRelease'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```

</details>

**Comment by mattbfb** [comment]
@robandpdx I did some digging through the build; the first error appears to be because the testing step expects Hermes to be cloned and built from the directory contained in the `HERMES_WS_DIR` environment variable. I'm not familiar with `actions/checkout`, but I'm guessing it's just a matter of adjusting the path where it checks out the repo (and possibly changing the current directory into that directory before running the build).

The second error appears to be a lack of a running android instance. Does the image being used contain (and launch) an Android simulator? The CircleCI version used an image that had an android simulator, and launched it using the `start-emulator-and-run-tests` command. (https://circleci.com/developer/orbs/orb/circleci/android)

**Comment by robandpdx** [comment]
> the testing step expects Hermes to be cloned and built from the directory contained in the `HERMES_WS_DIR` environment variable. I'm not familiar with `actions/checkout`, but I'm guessing it's just a matter of adjusting the path where it checks out the repo (and possibly changing the current directory into that directory before running the build).  

@mattbfb Thank you for the help here. I'll see if I adjust the `HERMES_WS_DIR` environment variable to make this work.

> The second error appears to be a lack of a running android instance. Does the image being used contain (and launch) an Android simulator? The CircleCI version used an image that had an android simulator, and launched it using the `start-emulator-and-run-tests` command. (https://circleci.com/developer/orbs/orb/circleci/android)

The `test-e2e` job is running inside the `reactnativecommunity/react-native-android:latest` container on `ubuntu-20.04`. On the host, I don't believe any android simulator exists. Would the android simulator be provided by the container, perhaps? Sorry for my ignorance here. Android development is not my forté.

**Comment by mattbfb** [comment]
@robandpdx I think that's all correct, and I see tests now appear to be passing!

**Comment by mattbfb** [comment]
@robandpdx This one is looking good and on its way to land. Thanks!

Can you perform the same porting for the "Static Hermes" project (https://github.com/facebook/hermes/tree/static_h)? It has a CircleCI build in the same location, but with a much simpler implementation (https://github.com/facebook/hermes/blob/static_h/.circleci/config.yml)

**Comment by robandpdx** [comment]
> Can you perform the same porting for the "Static Hermes" project (https://github.com/facebook/hermes/tree/static_h)? It has a CircleCI build in the same location, but with a much simpler implementation (https://github.com/facebook/hermes/blob/static_h/.circleci/config.yml)

I can. I'm in a holding pattern currently because our engagement has run out of hours. I believe more hours will be allocated to this effort in the not so distant future. When/if that happens, I'll get it done.

**Pull request closed without merging**
