### PR TITLE
(Cherry Pick) feat: add visionOS support

### PR DESCRIPTION
**Pull request by okwasniewski**
## Summary

This PR is a partial cherry-pick of this commit: dda343b80784fb75c791979c32ce943f8997dd37 from the `main` branch

Discussed offline with @cipolleschi in order to bring visionOS support to RN 0.74

## Test Plan

Not needed

### CODE REVIEW

**Comment by tmikov** [comment]
Is this the only change from that commit? The original change also changes CMakeLists.txt, a couple of scripts, etc?

**Comment by okwasniewski** [comment]
Thank you @tmikov I missed the CMakeLists.txt file. @cipolleschi mentioned the build scripts are not needed because they are separate in the React Native repo, so these should be the minimal changes needed to get this working

**Comment by tmikov** [comment]
@okwasniewski I believe the the CMake files and the scripts are used by RN. The only thing that is ignored is the pod file.

**Comment by cipolleschi** [comment]
The things that we use for React Native are in [this folder](https://github.com/facebook/react-native/tree/main/packages/react-native/sdks/hermes-engine).
To summarize, the build logic files we replace are:
- Cocoapods stuff (podspec and helpers)
- Some shell scripts (build-apple-framework, for example).

For everything  else, we rely on the Hermes repo. So yeah, if there are changes to other files other than the one above, we need to pick them as well.

Looking at the original commit, only `Logging.cpp` and the `CMakeList` needs to be picked. 
We can ignore the test folder.

@okwasniewski do you happen to know if we need some similar changes for tvOS? If yes, can we add another change on top of this? cc. @douglowder

One of the proposition of the [React Native Framework RFC](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0759-react-native-frameworks.md) is not to redistribute binaries: right now AVP and tvOS need to redistribute Hermes because you guys needs to rebuild it with the right slices. But we have an opportunity to unify all of them in Reac Native.

**Comment by okwasniewski** [comment]
Thanks for clarifying @cipolleschi.

Regarding tvOS, I think similar changes should be made as tvOS is also sharing lots of code with iOS. I would guess mostly to `CMakeList.txt` as the Logging.cpp import was strictly visionOS quirk

**Comment by douglowder** [comment]
@okwasniewski @cipolleschi the changes I made for tvOS are in https://github.com/react-native-tvos/hermes/tree/tvos-v0.74.0

**Comment by cipolleschi** [comment]
Cool, thanks @douglowder!
I think we have a couple of commits that we need to consider in order to make this work.
Are those changes already in `main`?

**Comment by douglowder** [comment]
@cipolleschi I merged my changes to current main: https://github.com/react-native-tvos/hermes/commit/be3f05c1a5b2e82b2f8aad36e1f3396f517ce67a

**Pull request merged**
