### PR TITLE
feat: enable bitcode

### PR DESCRIPTION
**Pull request by grabbou**
Bitcode is turned on by default in React Native and so, setting it here as well.

### CODE REVIEW

**Comment by tmikov** [comment]
There needs to be an option HERMES_ENABLE_BITCODE in the main CMake file, no?

**Comment by Huxpro** [comment]
@grabbou could you define the new option in the main file, similar to this: https://github.com/facebook/hermes/blob/070ffddf819831772e0f53445c952774f32db92b/CMakeLists.txt#L146 ?

**Comment by grabbou** [comment]
@Huxpro will do, I will also add some other missing flags that we have added the other day in a separate PR.

**Comment by grabbou** [comment]
@tmikov just saw your comment. Didn't need to set it, so not sure whether it "has" to be there by the means of working / not working. Would appreciate a bit of clarification so that I can deepen my understanding of CMake! 

I have tested this on my RNTester application (part of React Native PR) and it worked with bitcode enabled.

**Comment by tmikov** [comment]
@grabbou looks good now. The main reason to do it is that we want all flags controlling the build to be listed and documented in one place.

**Pull request closed without merging**
