### PR TITLE
[ts2flow] Convert built-in type primitives and literal types

### PR DESCRIPTION
**Pull request by seonggun-kim**
## Summary
[ts2flow] Convert built-in type primitives and literal types.

## Test Plan

Added unit and regression tests.

### CODE REVIEW

**Comment by tmikov** [comment]
We will probably need the parser and ESTree.def changes to be split in a separate PR, because we keep the parser synchronized between Hermes and Static Hermes. But before you do that, let's wait for @avp to review.

**Comment by avp** [comment]
This looks good to me, and the simple `NodeList` override in the visitor is a good idea.

But yeah we need to split off the ESTree.def/JSParserImpl changes because I will port those back to the `main` branch. Can you make a separate PR with just those changes against `static_h`? Then we can land them separately and not block on the sync to `main`.

**Comment by seonggun-kim** [comment]
Thank you for your review, @avp. I separated out the parser changes into #1115.

**Comment by avp** [comment]
5c498d75aa5462f1e9382041e0ee898a0b2cdeb5

**Pull request closed without merging**
