### PR TITLE
Add support for ES2023 `Array` non-mutating methods

### LINKED ISSUE #1078: Add support `Array.prototype.with`
## Problem

```tsx
// Hermes 0.72.x 🫠
typeof Array.prototype.with // undefined
```

## Solution

implment it or use polyfill

## Additional Context

Spec: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with
TS: [`es2023.array.d.ts`](https://github.com/microsoft/TypeScript/blob/b87e3018226262ea195a56abfb000a80b92c8f8c/src/lib/es2023.array.d.ts#L67)

### PR DESCRIPTION
**Pull request by robik**
### Overview

This PR implements partial support for new `Array.prototype` non-mutating methods introduced in ES2023. These are:

 - [`Array.prototype.toReversed()`](https://262.ecma-international.org/14.0/#sec-array.prototype.toreversed)
 - [`Array.prototype.toSpliced(start, skipCount, ...items)`](https://262.ecma-international.org/14.0/#sec-array.prototype.tospliced)
 - [`Array.prototype.with(index, value)`](https://262.ecma-international.org/14.0/#sec-array.prototype.with)

`Array.prototype.toSorted()` is implemented in separate PR #1298 as per request.

Other Array methods introduced in ES14 seem to already be implemented (`findLast`, `findLastIndex`).

Implementation for `TypedArray` methods are not included in this PR and will be provided in another one.

### Motivation

Aforementioned methods see support in all major browsers for quite some time [^toReversed][^toSorted][^toSpliced][^with]. Adding support brings hermes closer to full ES2023 coverage and will improve interoperability with browsers. It also should provide slight performance gains across all applications upon adoption. 

obraz

[^toReversed]: https://caniuse.com/?search=toReversed
[^toSorted]: https://caniuse.com/?search=toSorted
[^toSpliced]: https://caniuse.com/?search=toSpliced
[^with]: https://caniuse.com/?search=array.with

### Tasks

- [x] Implementation
- [x] Add tests
- [x] Format changes
- [ ] Add documentation somewhere?

### Implementation/review notes

This is my first contribution to this project. While I have some experience in C++ and have spent some time studying hermes codebase, there might be some slight misusages of your APIs (most notably handles and memory management) and breaking code-style. If so, please let me know and I will try fix them promptly 🙂

Most of the code was inspired/taken from already existing mutating functions. I also tried to apply optimisations that I've noticed in some of the methods (most notably fast path for array element accessing).

## Test Plan

Code is annotated with algorithm steps from EcmaScript specification for easier verification and maintenance.
I also added tests to verify that methods work as intended. There might be some more edge cases that might be covered based on your experience.

Quick test:

```sh
$ echo "[1,2,3,4,5].toReversed()" | ./bin/hermes
# >> [ 5, 4, 3, 2, 1, [length]: 5 ]

$ echo "[ 1, 2, 3, 4 ].toSpliced(2, 1, '3a', '3b', '3c')" | ./bin/hermes
# >> [ 1, 2, "3a", "3b", "3c", 4, [length]: 6 ]

$ echo "[1,0,3].with(1, 2)" | ./bin/hermes
# >> [ 1, 2, 3, [length]: 3 ]
```

---

Fixes #1078

### CODE REVIEW

**Comment by ljharb** [comment]
(fwiw after ES6, only the year should be used; so instead of ES14, it should be ES2023)

**Comment by tmikov** [comment]
@robik thank you very much for this PR. We are reviewing it - it looks generally good, we might have some minor comments.

**Comment by tmikov** [comment]
@robik there are some issue in toSorted(), caused partially by Hermes being non-spec compliant. Could you split this into two PRs - one containing everything but toSorted(), which we can probably land faster, and then toSorted(), which might require more time to sort out (pun intended).

**Comment by robik** [comment]
> @robik thank you very much for this PR. We are reviewing it - it looks generally good, we might have some minor comments.

Thanks! I'm ready for the review 🫡

> @robik there are some issues in toSorted(), caused partially by Hermes being non-spec compliant. Could you split this into two PRs - one containing everything but toSorted(), which we can probably land faster, and then toSorted(), which might require more time to sort out (pun intended).

Sure! I've moved toSorted() implementation to new PR #1298

**Comment by tmikov** [comment]
@robik thanks a lot! This looks good, we are landing it.

**Pull request closed without merging**
