### PR TITLE
python3 not python for apt

### PR DESCRIPTION
**Pull request by alexsch01**

### CODE REVIEW

**Comment by tmikov** [comment]
This is a change in generated assets.

**Comment by alexsch01** [comment]
@tmikov Ok

Btw for https://hermesengine.dev/docs/building-and-running, in the **apt** section it has "python" instead of "python3"

**Comment by tmikov** [comment]
https://github.com/facebook/hermes/blob/ab220c0e14c904df82982d363c221dbba7cc78a0/doc/BuildingAndRunning.md?plain=1#L16

**Comment by tmikov** [comment]
The website hasn't been regenerated.

**Pull request closed without merging**
